version: "3.0"

services:
  sadaparcel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sadaparcel
