version: "3.0"

services:
  sadaparcel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - config/env/.env.dev

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sadaparcel
      - redis
    env_file:
      - config/env/.env.dev
